### ISSUE TITLE
document agent filtering

### ISSUE THREAD

**Issue by hnykda** [drone/docs#364]
(pasted from [here](https://github.com/drone/drone/issues/2491))

Hi,

it seems that agents can already filter builds based on some criteria, but I am unable to find any resource which would tell me how to do it and I am unable to parse it from go.

I haven't found a word about labels or agent selection in docs, not in the [old](http://docs.drone.io/getting-started/) nor [new](http://readme.drone.io) (?). I am not even sure it should be done on the agent side as env var or in the `.drone.yml`. Therefore, I consider this as an issue.

I found mentions and relevant code on these:

* https://discourse.drone.io/t/drone-agent-filtering/2614 
* https://github.com/drone/drone/issues/2472
* #2200 
* https://github.com/drone/drone/issues/2171#issuecomment-327589521
* https://github.com/drone/expr/blob/master/selector_test.go
* https://github.com/drone/drone/pull/2198
* https://github.com/drone/drone/pull/2199
* https://github.com/drone/drone/pull/2442

Is someone able to give me a short summary or reference, at least something we can extrapolate based on the source code?

**Comment by SmajeNz0** [comment]
Hello Daniel,

I think it should read labels instead of label. I struggled to have it working, but once i added the s ... and formatted the filter like below, it worked.

Don't use the quotation marks for the expression in DRONE_FILTER and use ' before and after the number. Note the space before and after == .

HTH

-----------------------------------------------------
DRONE_FILTER=ram == '16'
-----------------------------------------------------
labels:
  - ram=16
-----------------------------------------------------

**Comment by hnykda** [comment]
Hey. Thanks for the info. Any chance you could try any other filters specified here: https://github.com/drone/docs/pull/365 ? Also, what's your version?

**Comment by SmajeNz0** [comment]
Hello

I tested on 0.8.7, but as you already know, they are changing the behavior in 0.9.

https://docs.drone.io/reference/agent/drone-runner-labels/
https://docs.drone.io/config/pipeline/nodes/

I am upgrading to 0.9 now.

Cheers,

**Comment by tboerger** [comment]
Closing this as it's properly documented for 1.0.0 at https://docs.drone.io/reference/agent/drone-runner-labels/ and https://docs.drone.io/config/pipeline/nodes/
